In [40]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(A)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [42]:
def Gauss_Seidel(A,b,itmax=1000,error = 1e-10):
    M,N = A.shape
    
    x = np.zeros(N)
    
    sumk = np.zeros_like(x)
    
    x = [13,20,-1]
    
    it = 0 
    
    s= np.shape(b)
    v = np.ones(s)
    
    residuo = np.linalg.norm( b - np.dot(A,x) )

    diferencia = np.ones( N, dtype=float)
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
              if (j !=i ):
                sum_ = sum_ + A[i,j]*v[j]
            
            new = (b[i]-sum_)/A[i,i]
            diferencia[i] = np.abs(new-v[i])
            v[i] = new
        
        
        
        
              

        
        print(x)
        residuo = np.linalg.norm( b - np.dot(A,x) )
        
    return x,it,residuo


In [43]:
Gauss_Seidel(A,b,itmax=1000,error = 1e-10)

[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]
[13, 20, -1]

([13, 20, -1], 1000, 58.60887304837041)