In [33]:

import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

In [50]:
xi=0.1
xf=1.1
h=(xf-xi)/100
X=np.linspace(xi,xf,100)

In [51]:
def function1(x):
  return np.sqrt(np.tan(x))

function(X)

array([0.31675649, 0.3324877 , 0.34754036, 0.36200213, 0.37594412,
       0.38942502, 0.40249393, 0.4151925 , 0.42755642, 0.43961656,
       0.45139989, 0.46293013, 0.47422832, 0.48531321, 0.49620162,
       0.50690875, 0.51744838, 0.52783304, 0.53807423, 0.54818253,
       0.55816767, 0.5680387 , 0.57780402, 0.58747148, 0.59704842,
       0.60654173, 0.61595793, 0.62530317, 0.63458326, 0.64380377,
       0.65296998, 0.66208694, 0.67115952, 0.68019237, 0.68919   ,
       0.69815675, 0.70709684, 0.71601438, 0.72491335, 0.73379765,
       0.74267111, 0.75153746, 0.76040041, 0.76926359, 0.77813058,
       0.78700497, 0.79589027, 0.80479002, 0.81370773, 0.8226469 ,
       0.83161105, 0.84060371, 0.84962844, 0.8586888 , 0.86778841,
       0.87693092, 0.88612003, 0.8953595 , 0.90465315, 0.91400487,
       0.92341863, 0.93289849, 0.94244861, 0.95207324, 0.96177675,
       0.97156365, 0.98143855, 0.99140622, 1.00147161, 1.01163979,
       1.02191604, 1.03230582, 1.04281481, 1.05344889, 1.06421

In [52]:
def DerivativeP(f,x):
  return (f(x+h)-f(x))/h
DerivativeP(function1,X)

array([1.55774182, 1.49051899, 1.43198324, 1.38049463, 1.33482012,
       1.29401234, 1.25732977, 1.2241826 , 1.19409507, 1.16667864,
       1.14161251, 1.11862919, 1.09750369, 1.07804527, 1.06009106,
       1.0435011 , 1.02815442, 1.01394586, 1.00078364, 0.98858724,
       0.97728577, 0.96681658, 0.95712416, 0.94815913, 0.93987749,
       0.93223994, 0.92521132, 0.91876011, 0.91285804, 0.9074797 ,
       0.90260229, 0.89820532, 0.89427038, 0.89078096, 0.8877223 ,
       0.88508118, 0.88284585, 0.88100587, 0.87955205, 0.87847633,
       0.87777174, 0.8774323 , 0.87745298, 0.87782965, 0.87855902,
       0.87963865, 0.88106687, 0.88284276, 0.88496617, 0.88743767,
       0.89025853, 0.89343074, 0.89695701, 0.90084074, 0.90508602,
       0.90969768, 0.91468128, 0.9200431 , 0.92579019, 0.93193038,
       0.93847229, 0.94542538, 0.95279999, 0.96060734, 0.96885961,
       0.97756997, 0.98675264, 0.99642291, 1.00659727, 1.01729343,
       1.02853042, 1.04032864, 1.05271001, 1.06569803, 1.07931

In [53]:
def DerivativeC(f,x):
  return (f(x+h)-f(x-h)/2*h)
DerivativeC(function,X)

array([0.33083188, 0.3458083 , 0.36019698, 0.37406863, 0.3874816 ,
       0.40048474, 0.41311944, 0.42542122, 0.43742078, 0.44914495,
       0.46061733, 0.47185884, 0.48288814, 0.49372196, 0.50437542,
       0.51486222, 0.52519484, 0.53538473, 0.54544239, 0.55537752,
       0.56519911, 0.57491553, 0.58453458, 0.59406357, 0.60350935,
       0.61287841, 0.62217686, 0.63141051, 0.64058486, 0.64970519,
       0.65877652, 0.66780369, 0.67679133, 0.68574393, 0.69466581,
       0.70356116, 0.71243407, 0.72128851, 0.73012835, 0.7389574 ,
       0.74777939, 0.75659799, 0.76541681, 0.77423944, 0.78306941,
       0.79191026, 0.80076547, 0.80963855, 0.81853299, 0.82745229,
       0.83639995, 0.84537952, 0.85439454, 0.86344861, 0.87254537,
       0.8816885 , 0.89088173, 0.90012887, 0.90943379, 0.91880044,
       0.92823286, 0.93773518, 0.94731164, 0.95696659, 0.9667045 ,
       0.97652997, 0.98644776, 0.99646276, 1.00658005, 1.01680486,
       1.02714263, 1.03759901, 1.04817985, 1.05889126, 1.06973

In [55]:
x = sym.Symbol('x',Real=True)
y=sym.sqrt(sym.tan(x))
df=sym.diff(y,x)
 
derivadas= sym.lambdify(x,y)
derivadas(X) 


array([0.31675649, 0.3324877 , 0.34754036, 0.36200213, 0.37594412,
       0.38942502, 0.40249393, 0.4151925 , 0.42755642, 0.43961656,
       0.45139989, 0.46293013, 0.47422832, 0.48531321, 0.49620162,
       0.50690875, 0.51744838, 0.52783304, 0.53807423, 0.54818253,
       0.55816767, 0.5680387 , 0.57780402, 0.58747148, 0.59704842,
       0.60654173, 0.61595793, 0.62530317, 0.63458326, 0.64380377,
       0.65296998, 0.66208694, 0.67115952, 0.68019237, 0.68919   ,
       0.69815675, 0.70709684, 0.71601438, 0.72491335, 0.73379765,
       0.74267111, 0.75153746, 0.76040041, 0.76926359, 0.77813058,
       0.78700497, 0.79589027, 0.80479002, 0.81370773, 0.8226469 ,
       0.83161105, 0.84060371, 0.84962844, 0.8586888 , 0.86778841,
       0.87693092, 0.88612003, 0.8953595 , 0.90465315, 0.91400487,
       0.92341863, 0.93289849, 0.94244861, 0.95207324, 0.96177675,
       0.97156365, 0.98143855, 0.99140622, 1.00147161, 1.01163979,
       1.02191604, 1.03230582, 1.04281481, 1.05344889, 1.06421