In [9]:
import numpy as np

In [10]:
b = np.array([-3.,
              -3.,
               8.,
              9.])
    

A= np.array([[3,1,-1],
             [1,2,0],
             [0,1,2],
             [1,1,-1]])

u1= A[:,0]
u2= A[:,1]
u3= A[:,2]

u1

array([3, 1, 0, 1])

x = A^T@b
 

In [11]:
AT = np.zeros((3,4))

AT[:,0] = A[0,:]
AT[:,1] = A[1,:]
AT[:,2] = A[2,:]
AT[:,3] = A[3,:]

AT

array([[ 3.,  1.,  0.,  1.],
       [ 1.,  2.,  1.,  1.],
       [-1.,  0.,  2., -1.]])

In [18]:
x = np.linalg.pinv(A)@b 
np.linalg.pinv(A)

array([[ 0.46268657, -0.2238806 ,  0.14925373, -0.1641791 ],
       [-0.25373134,  0.47761194,  0.01492537,  0.28358209],
       [ 0.14179104, -0.14925373,  0.43283582, -0.2761194 ]])

In [13]:
pw = A@x
np.round (pw)

array([-2.,  3.,  4.,  0.])

In [14]:
def gramsch(u):
  tam=u.shape
  m = tam[0]
  v = np.zeros((m))
  v[0]=u[0]

  for k in range(0,m):
    v[k]=u[k]
    for j in range(k):
      v[k] = (v[k] - (np.dot(v[k],u[j]))) / (np.dot(u[j],u[j]))*u[j]
    return v



In [15]:
v1 = u1
v2 = u2 - (np.dot(u2,v1)/np.linalg.norm(v1)**2)*v1
v3 = u3 - (np.dot(u3,v1)/np.linalg.norm(v1)**2)*v1 - (np.dot(u3,v2)/np.linalg.norm(v2)**2)*v2
v1,v2,v3



(array([3, 1, 0, 1]),
 array([-0.63636364,  1.45454545,  1.        ,  0.45454545]),
 array([ 0.46341463, -0.48780488,  1.41463415, -0.90243902]))

In [16]:
base= np.zeros((3,4))
base
base[0,:] = v1/np.linalg.norm(v1)
base[1,:] = v2/np.linalg.norm(v2)
base[2,:] = v3/np.linalg.norm(v3)
v1 = base[0,:] 
v2 = base[1,:] 
v3 = base[2,:] 
base


array([[ 0.90453403,  0.30151134,  0.        ,  0.30151134],
       [-0.32961713,  0.75341057,  0.51796977,  0.2354408 ],
       [ 0.25633581, -0.26982716,  0.78249877, -0.49918025]])

In [17]:
c1 = b@v1
c2 = b@v2
c3 = b@v3

def pw (g):
  wp= c1*v1+c2*v2+c3*v3
  return wp

np.round(pw(b))

array([-2.,  3.,  4., -0.])